[functions.admin-actions]
verify_jwt = false

[functions.verify-topup-slip]
verify_jwt = false

[functions.auto-shop-schedule]
verify_jwt = false

[functions.send-admin-line]
verify_jwt = false

[functions.send-admin-telegram]
verify_jwt = false
