-- ============================================
-- Scheduled order automation tracking columns
-- ============================================
-- Used by edge function `process-scheduled-orders` to avoid duplicate
-- reminders/release notifications.

ALTER TABLE public.bookings
ADD COLUMN IF NOT EXISTS scheduled_reminder_sent_at timestamptz,
ADD COLUMN IF NOT EXISTS scheduled_release_processed_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_bookings_scheduled_pending
ON public.bookings (scheduled_at)
WHERE scheduled_at IS NOT NULL
  AND status IN ('pending', 'pending_merchant', 'preparing');

CREATE INDEX IF NOT EXISTS idx_bookings_scheduled_reminder_pending
ON public.bookings (scheduled_at)
WHERE scheduled_at IS NOT NULL
  AND scheduled_reminder_sent_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_bookings_scheduled_release_pending
ON public.bookings (scheduled_at)
WHERE scheduled_at IS NOT NULL
  AND scheduled_release_processed_at IS NULL;

COMMENT ON COLUMN public.bookings.scheduled_reminder_sent_at IS
'When pre-scheduled reminder notifications were generated by scheduler job.';

COMMENT ON COLUMN public.bookings.scheduled_release_processed_at IS
'When scheduled order was released/processed by scheduler job at or after scheduled_at.';
